name: Database Migration

on:
  workflow_dispatch:
  
jobs:
  database-migration:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      CONNECTIONSTRING: ${{ secrets.CONNECTIONSTRING }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Install EF Core
        run: dotnet tool install --global dotnet-ef
        env:
          NUGET_XMLDOC_MODE: skip
      - name: Restore dependencies
        run: dotnet restore
        working-directory: api
      - name: Add migration
        run: dotnet ef migrations add init
        working-directory: api
      - name: Update database
        run: dotnet ef database update -- --connection "${{ env.CONNECTIONSTRING }}" --environment Production
        working-directory: api